# Generated by Django 4.0.3 on 2022-08-01 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('question1', models.TextField()),
                ('option_one1', models.CharField(max_length=50)),
                ('option_two1', models.CharField(max_length=50)),
                ('option_three1', models.CharField(max_length=50)),
                ('option_four1', models.CharField(max_length=50)),
                ('ans1', models.CharField(max_length=50)),
                ('yourAnswer1', models.CharField(max_length=50)),
                ('question2', models.TextField()),
                ('option_one2', models.CharField(max_length=50)),
                ('option_two2', models.CharField(max_length=50)),
                ('option_three2', models.CharField(max_length=50)),
                ('option_four2', models.CharField(max_length=50)),
                ('ans2', models.CharField(max_length=50)),
                ('yourAnswer2', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('option_one', models.CharField(max_length=50)),
                ('option_two', models.CharField(max_length=50)),
                ('option_three', models.CharField(max_length=50)),
                ('option_four', models.CharField(max_length=50)),
                ('ans', models.CharField(max_length=50)),
            ],
        ),
    ]
